
{{- with .Values.users }}
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource
spec:
  rbac:
    defaultPolicy: 'role:none'
    policy: |-
      # Access Control
      p, role:none, applications, get, */*, deny
      p, role:none, certificates, get, *, deny
      p, role:none, clusters, get, *, deny
      p, role:none, repositories, get, *, deny
      p, role:none, projects, get, *, deny
      p, role:none, accounts, get, *, deny
      p, role:none, gpgkeys, get, *, deny
      g, system:cluster-admins, role:admin
      # Adding Roles for specific group to see clusters
{{- range $user := $.Values.users }}
      p, role:{{ $user }}, clusters, get, https://kubernetes.default.svc, allow
      g, {{ $user }}, role:{{ $user }}
{{- end }}
{{- end }}