{{- range $user := $.Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $user }}-gitops-guide-user-role-binding
subjects:
- kind: Group
  name: {{ $user }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-guide-user-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ $user }}
users:
  - {{ $user }}
---
{{- end }}