{{- range $user := $.Values.users }}
{{- $var_user := $user }}
{{- range $namespace := $.Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $var_user }}-{{ $namespace }}
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
---
#Add user to namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $var_user }}-namespace
  namespace: {{ $var_user }}-{{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: {{ $var_user }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $var_user }}-gitops-role-binding
  namespace: {{ $var_user }}-{{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $var_user }}-gitops-role-binding-monitoring-edit
  namespace: {{ $var_user }}-{{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

---
{{- end }}
{{- end }}