{{- if .Values.bluegreen.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-blue-green
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
  - name: SOURCE_GIT_URL
    type: string
    default: https://github.com/{{ .Values.github.repository }}/cloud-native-deployment-strategies
    description: The application git repository url
  - name: SOURCE_GIT_REVISION
    type: string
    default: blue-green
    description: The application git repository revision
  - name: CONTEXT_DIR
    type: string
    default: "helm/quarkus-helm-umbrella/chart"
    description: The subdirectory in the git repository
  - name: NAMESPACE
    type: string
    default: {{ .Values.namespace }}
    description: namespace
  - name: VALUES_FILE
    type: string
    default: {{ .Values.bluegreen.valuesyaml }} 
  - name: APP
    type: string
    description: discounts or products
  - name: NEW_IMAGE_TAG
    type: string
    default: None
  - name: REPLICA_COUNT
    type: string
    default: None
  - name: STEP
    type: string
  - name: GIT_USER_NAME
    type: string
    default: {{ .Values.github.user }}
  - name: GIT_USER_EMAIL
    type: string
    default: {{ .Values.github.mail }}
  - name: JQ_PATH
    type: string
    default: .metadata  
  - name: LABEL
    type: string
    default: .version  

  workspaces:
  - name: app-source

  tasks:
  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source


  - name: get-offline-colour
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: openshift-client
    params:
    - name: SCRIPT
      value: |
        oc get service $(params.APP)-umbrella-offline -n $(params.NAMESPACE) --output="jsonpath={.spec.selector.version}" > $(workspaces.manifest-dir.path)/version
        cat $(workspaces.manifest-dir.path)/version
    workspaces:
    - name: manifest-dir
      workspace: app-source

  - name: create-result-colour
    runAfter:
    - get-offline-colour
    taskSpec:
      metadata: {}
      steps:
      - name: set-results
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/usr/bin/env bash
          cat $(workspaces.source.path)/version
          cat $(workspaces.source.path)/version > tekton/results/version
      results:
        - name: version	
          type: string	
      spec: null
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: change-new-image-tag
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: NEW_IMAGE_TAG
        value: $(params.NEW_IMAGE_TAG) 
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version)
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)
      - name: REPLICA_COUNT
        value: $(params.REPLICA_COUNT)
    taskSpec:
      metadata: {}
      params:
      - name: CONTEXT_DIR
        type: string
      - name: APP
        type: string
      - name: NEW_IMAGE_TAG
        type: string
      - name: COLOUR
        type: string
      - name: VALUES_FILE
        type: string
      - name: REPLICA_COUNT
        type: string
      spec: null
      steps:
      - name: change-new-image-tag
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          sed -i '/$(params.APP)-$(params.COLOUR)/{n;n;n;n;s/.*/      tag: $(params.NEW_IMAGE_TAG)/}' $(params.VALUES_FILE)
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-new-image-tag
    runAfter:
    - change-new-image-tag
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    taskRef:
      kind: Task
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP)-$(tasks.create-result-colour.results.version)  new image tag $(params.NEW_IMAGE_TAG)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source
  - name: get-application-url-new-image-tag
    runAfter:
    - commit-new-image-tag
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    taskRef:
      kind: Task
      name: openshift-client
    params:
    - name: SCRIPT
      value: |
        host=$(oc get routes $(params.APP)-umbrella-offline -n $(params.NAMESPACE) -o=jsonpath='{.spec.host}')
        url=https://${host}/$(params.APP)
        echo $url > $(workspaces.manifest-dir.path)/url
        cat $(workspaces.manifest-dir.path)/url
    workspaces:
    - name: manifest-dir
      workspace: app-source
  - name: e2e-test-new-image-tag
    runAfter:
    - get-application-url-new-image-tag
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    params:
      - name: TARGET_VERSION
        value: $(params.NEW_IMAGE_TAG)
      - name: JQ_PATH
        value: $(params.JQ_PATH)
      - name: LABEL
        value: $(params.LABEL)
    taskRef:
      kind: Task
      name: shop-e2e-test
    timeout: "8m30s"
    workspaces:
    - name: source
      workspace: app-source
  - name: change-configuration
    runAfter:
    - e2e-test-new-image-tag
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version)
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)        
    taskSpec:
      metadata: {}
      params:
      - name: CONTEXT_DIR
        type: string
      - name: APP
        type: string
      - name: COLOUR
        type: string
      - name: VALUES_FILE
        type: string   
      spec: null
      steps:
      - name: change-configuration
        resources: {}
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          sed -i '/$(params.APP)-$(params.COLOUR)/{n;n;s/.*/    replicaCount: 0/}' $(params.VALUES_FILE)
          sed -i '/$(params.APP)-$(params.COLOUR)/{n;n;n;n;n;s/.*/  mode: online/}' $(params.VALUES_FILE)
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-configuration
    runAfter:
    - change-configuration
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    taskRef:
      kind: Task
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP)-$(tasks.create-result-colour.results.version) change configuration"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source

  - name: get-deployment-replicas
    runAfter:
    - commit-configuration
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    taskRef:
      kind: Task
      name: openshift-client
    params: 
    - name: SCRIPT
      value: |
        replicas=-1
        while [ $replicas != 0 ]
        do
          replicas=$(oc get deployments $(params.APP)-$(tasks.create-result-colour.results.version) -n $(params.NAMESPACE) --output="jsonpath={.spec.replicas}" 2>&1)
          echo $replicas
          sleep 5
        done
        oc get deployments $(params.APP)-$(tasks.create-result-colour.results.version) -n $(params.NAMESPACE) --output="jsonpath={.spec.replicas}" > $(workspaces.manifest-dir.path)/replicas
        cat $(workspaces.manifest-dir.path)/replicas
    workspaces:
    - name: manifest-dir
      workspace: app-source

  - name: change-scale-up
    runAfter:
    - get-deployment-replicas
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: REPLICA_COUNT
        value: $(params.REPLICA_COUNT) 
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version)
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)        
    taskSpec:
      metadata: {}
      params:
      - name: CONTEXT_DIR
        type: string
      - name: APP
        type: string
      - name: REPLICA_COUNT
        type: string
      - name: COLOUR
        type: string
      - name: VALUES_FILE
        type: string
      spec: null
      steps:
      - name: change-scale-up
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          sed -i '/$(params.APP)-$(params.COLOUR)/{n;n;s/.*/    replicaCount: $(params.REPLICA_COUNT)/}' $(params.VALUES_FILE)
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-scale-up
    runAfter:
    - change-scale-up
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    taskRef:
      kind: Task
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP)-$(tasks.create-result-colour.results.version) replicaCount: $(params.REPLICA_COUNT)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source

  - name: change-switch
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["switch"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version) 
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)         
    taskSpec:
      metadata: {}
      params:
      - name: CONTEXT_DIR
        type: string
      - name: APP
        type: string
      - name: COLOUR
        type: string
      - name: VALUES_FILE
        type: string
      spec: null
      steps:
      - name: change-switch
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          sed -i '/$(params.APP)NetworkingOnline/{n;s/.*/  version: $(params.COLOUR)/}' $(params.VALUES_FILE)
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-switch
    runAfter:
    - change-switch
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["switch"]
    taskRef:
      kind: Task
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP) switch online to $(tasks.create-result-colour.results.version)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source
  - name: change-scale-down-offline
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["scale-down-offline"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: NEW_IMAGE_TAG
        value: $(params.NEW_IMAGE_TAG) 
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version) 
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)            
    taskSpec:
      metadata: {}
      params:
      - name: CONTEXT_DIR
        type: string
      - name: APP
        type: string
      - name: NEW_IMAGE_TAG
        type: string
      - name: COLOUR
        type: string 
      - name: VALUES_FILE
        type: string
      spec: null
      steps:
      - name: scale-down-offline
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/bin/bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          COLOUR=$(params.COLOUR)
          if [ $COLOUR = "blue" ]
          then
            NEW_COLOUR="green"
          else
            NEW_COLOUR="blue"
          fi
          echo $NEW_COLOUR

          sed -i "/$(params.APP)NetworkingOffline/{n;s/.*/  version: $NEW_COLOUR/}" $(params.VALUES_FILE)
          
          sed -i "/$(params.APP)-$NEW_COLOUR/{n;n;s/.*/    replicaCount: 1/}" $(params.VALUES_FILE)
          sed -i "/$(params.APP)-$NEW_COLOUR/{n;n;n;n;s/.*/      tag: $(params.NEW_IMAGE_TAG)/}" $(params.VALUES_FILE)
          sed -i "/$(params.APP)-$NEW_COLOUR/{n;n;n;n;n;s/.*/  mode: offline/}" $(params.VALUES_FILE)
          
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-scale-down-offline
    runAfter:
    - change-scale-down-offline
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["scale-down-offline"]
    taskRef:
      kind: Task
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP) scale down offline"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source

  - name: switch-rollback
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["switch-rollback"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version) 
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)         
    taskSpec:
      metadata: {}
      params:
      - name: CONTEXT_DIR
        type: string
      - name: APP
        type: string
      - name: COLOUR
        type: string 
      - name: VALUES_FILE
        type: string
      spec: null
      steps:
      - name: change-switch
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)

          COLOUR=$(params.COLOUR)
          if [ $COLOUR = "blue" ]
          then
            NEW_COLOUR="green"
          else
            NEW_COLOUR="blue"
          fi
          echo $NEW_COLOUR

          sed -i "/$(params.APP)NetworkingOnline/{n;s/.*/  version: $NEW_COLOUR/}" $(params.VALUES_FILE)
          
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-switch-rollback
    runAfter:
    - switch-rollback
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["switch-rollback"]
    taskRef:
      kind: Task
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP) switch-rollback online to $(tasks.create-result-colour.results.version)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: workspace-pvc-shop-cd-new-version
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}