{{- if .Values.pipeline.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shop-e2e-test
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
  - name: TARGET_VERSION
  - name: JQ_PATH
  - name: LABEL
  steps:
  - name: set-results
    image: quay.io/jsimas/alpine-curl-jq:1.0
    script: |
      version="none"
      cat $(workspaces.source.path)/url
      while [[ "$version" != "$(params.TARGET_VERSION)" ]]
      do
        sleep 5
        curl -k $(cat $(workspaces.source.path)/url) | jq -r '$(params.JQ_PATH)' > metadata
        cat metadata
        version=$(jq -r '$(params.LABEL)' metadata)
        echo $version
      done
  workspaces:
  - name: source
{{ end }}
