{{- if .Values.pipeline.applications.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: {{ .Values.namespace }}
  annotations:
    tekton.dev/docker-0: 'https://quay.io/dseveria'
data:
  .dockerconfigjson: {{ .Values.pipeline.applications.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{ end }}