apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-change-replicas-
spec:
  pipelineRef:
    name: pipeline-blue-green-environments
  params:
  - name: APP
    value: products
  - name: ENV
    value: stage
  - name: COLOUR
    value: green
  - name: STEP
    value: "change-replicas"
  - name: REPLICA_COUNT
    value: "4"
  - name: NAMESPACE
    value: "user1-stage"
  - name: REPO_FULL_NAME
    value: davidseve/argocd-environments-promotion
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version